api_version = "2026-01"

[[extensions]]
name = "Handling Fee Checkout Extension"
handle = "handling-fee-checkout"
uid = "18ea2d5a-008f-81c1-217a-86f71719bdedde2e3160"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/Checkout.js"
  target = "purchase.checkout.cart-line-list.render-after"

[extensions.capabilities]
  network_access = true
